# Attogram Currency Exchange Rates
# <https://github.com/attogram/currency-exchange-rates>
# <https://travis-ci.org/attogram/currency-exchange-rates>
language: php
php:
  - '7.0'
  - '7.1'
  - '7.2'
  - '7.3'
  - nightly
matrix:
  allow_failures:
    - php: nightly
  fast_finish: true
before_script:
  - composer install
script:
  # Test Install via composer create-project
  - composer create-project attogram/currency-exchange-rates your-install-directory
  - chmod 777 your-install-directory/db
  - cp your-install-directory/custom/config.example.php your-install-directory/custom/config.php
  - php your-install-directory/cli/update.php
  # PHP Lint all the things
  - if find . -name "*.php" -exec php -l {} 2>&1 \; | grep "error,"; then exit 1; fi;
  # Unit Tests
#  - phpunit tests
